development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("HEROKU_REDIS_TEAL_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: notify_me_production
